#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/cb20d98a-b2f6-441f-8a1b-b217ee87996d 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool rele;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#define rele_pin 12
#define rele_ligado 0 
#define rele_desligado 1

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  
  pinMode(rele_pin, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
}


/*
  Since Rele is READ_WRITE variable, onReleChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onReleChange()  {
  // Add your code here to act upon Rele change
  // Habilitando a irrigação
  if (digitalRead(rele) == rele_desligado) {
    digitalWrite(rele, rele_ligado);
    /*digitalWrite(sensor_humidade, 0);
    if (estagio != 0) {
      estagio = 2;
      send_informations = 1;
    }*/
  }

  // Desabilitando a irrigação
  else {
    digitalWrite(rele, rele_desligado);
    /*if (estagio != 2) {
      tempo_retornar_logica = tempo_l;
      if (estagio != 0) {
        estagio = 2;
        send_informations = 1;
      }*/
    }
}

